Updated deploy.yaml file

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -41,12 +41,16 @@ jobs:
           echo 'Adding new inbound rules...'
           ADD_RULES_RESULT=$(aws ec2 authorize-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port 22 --cidr "$GITHUB_RUNNER_IP/32" 2>&1)
           if [[ $? -ne 0 ]]; then
-            echo "Failed to add a new inbound rule: $ADD_RULES_RESULT"
+            echo "Failed to add a new inbound rule:"
+            echo "Exit code: $?"
+            echo "Error message: $ADD_RULES_RESULT"
             exit 1
           fi
           ADD_RULES_RESULT=$(aws ec2 authorize-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port 80 --cidr "$GITHUB_RUNNER_IP/32" 2>&1)
           if [[ $? -ne 0 ]]; then
-            echo "Failed to add a new inbound rule: $ADD_RULES_RESULT"
+            echo "Failed to add a new inbound rule:"
+            echo "Exit code: $?"
+            echo "Error message: $ADD_RULES_RESULT"
             exit 1
           fi
 
