Updated deploy.yaml file

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -50,11 +50,16 @@ jobs:
           ADD_RULES_RESULT=$(aws ec2 authorize-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port 80 --cidr "$GITHUB_RUNNER_IP/32" 2>&1 || true)
           echo "Error message (if any): $ADD_RULES_RESULT"
           
-          # Update the description of the new rules
-          echo 'Updating the description of the new rules to GitHub Action...'
-          NEW_RULES_QUERY="SecurityGroups[].IpPermissions[] | [?(FromPort==\`22\` && ToPort==\`22\` && IpRanges[0].CidrIp==\`$GITHUB_RUNNER_IP/32\`) || (FromPort==\`80\` && ToPort==\`80\` && IpRanges[0].CidrIp==\`$GITHUB_RUNNER_IP/32\`)]"
-          NEW_RULES=$(aws ec2 describe-security-groups --group-id "$SECURITY_GROUP_ID" --query "$NEW_RULES_QUERY" --output json)
-          aws ec2 update-security-group-rule-descriptions-ingress --group-id "$SECURITY_GROUP_ID" --ip-permissions "$NEW_RULES" --cli-input-json '{"IpPermissions":[{"FromPort":22,"ToPort":22,"IpProtocol":"tcp","IpRanges":[{"CidrIp":"'"$GITHUB_RUNNER_IP"'/32","Description":"GitHub Action"}]},{"FromPort":80,"ToPort":80,"IpProtocol":"tcp","IpRanges":[{"CidrIp":"'"$GITHUB_RUNNER_IP"'/32","Description":"GitHub Action"}]}]}'
+          # If adding new rules is successful, update the description
+          if [[ ! "$ADD_RULES_RESULT" =~ .*RulesPerSecurityGroupLimitExceeded.* ]]; then
+            # Update the description of the new rules
+            echo 'Updating the description of the new rules to GitHub Action...'
+            NEW_RULES_QUERY="SecurityGroups[].IpPermissions[] | [?(FromPort==\`22\` && ToPort==\`22\` && IpRanges[0].CidrIp==\`$GITHUB_RUNNER_IP/32\`) || (FromPort==\`80\` && ToPort==\`80\` && IpRanges[0].CidrIp==\`$GITHUB_RUNNER_IP/32\`)]"
+            NEW_RULES=$(aws ec2 describe-security-groups --group-id "$SECURITY_GROUP_ID" --query "$NEW_RULES_QUERY" --output json)
+            aws ec2 update-security-group-rule-descriptions-ingress --group-id "$SECURITY_GROUP_ID" --ip-permissions "$NEW_RULES" --cli-input-json '{"IpPermissions":[{"FromPort":22,"ToPort":22,"IpProtocol":"tcp","IpRanges":[{"CidrIp":"'"$GITHUB_RUNNER_IP"'/32","Description":"GitHub Action"}]},{"FromPort":80,"ToPort":80,"IpProtocol":"tcp","IpRanges":[{"CidrIp":"'"$GITHUB_RUNNER_IP"'/32","Description":"GitHub Action"}]}]}'
+          else
+            echo "Could not add new rules due to reaching the maximum number of rules per security group."
+          fi
           
           echo "Waiting 2 minutes for the security group changes to take effect"
           sleep 120
