Updated deploy.yaml file

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -39,8 +39,16 @@ jobs:
 
           # Add new inbound rules without description
           echo 'Adding new inbound rules...'
-          aws ec2 authorize-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port 22 --cidr "$GITHUB_RUNNER_IP/32"
-          aws ec2 authorize-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port 80 --cidr "$GITHUB_RUNNER_IP/32"
+          ADD_RULES_RESULT=$(aws ec2 authorize-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port 22 --cidr "$GITHUB_RUNNER_IP/32" 2>&1)
+          if [[ $? -ne 0 ]]; then
+            echo "Failed to add a new inbound rule: $ADD_RULES_RESULT"
+            exit 1
+          fi
+          ADD_RULES_RESULT=$(aws ec2 authorize-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port 80 --cidr "$GITHUB_RUNNER_IP/32" 2>&1)
+          if [[ $? -ne 0 ]]; then
+            echo "Failed to add a new inbound rule: $ADD_RULES_RESULT"
+            exit 1
+          fi
 
           # Update the description of the new rules
           echo 'Updating the description of the new rules to GitHub Action...'
